/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 11 21:34:23 GMT 2025
 */

package sqlancer.evosuite.postgres;

import static org.junit.jupiter.api.Assertions.*;

import java.util.LinkedList;
import java.util.List;
import org.junit.jupiter.api.Test;
import sqlancer.postgres.PostgresOptions;
import sqlancer.postgres.PostgresOracleFactory;

public class PostgresOptions_ESTest {

    @Test
    public void test0() throws Throwable {
        PostgresOptions postgresOptions0 = new PostgresOptions();
        postgresOptions0.oracle = postgresOptions0.oracle;
        postgresOptions0.oracle = null;
        postgresOptions0.getTestOracleFactory();
        assertTrue(postgresOptions0.testCollations);
    }

    @Test
    public void test1() throws Throwable {
        PostgresOptions postgresOptions0 = new PostgresOptions();
        LinkedList<PostgresOracleFactory> linkedList0 = new LinkedList<PostgresOracleFactory>();
        postgresOptions0.oracle = (List<PostgresOracleFactory>) linkedList0;
        postgresOptions0.getTestOracleFactory();
        assertTrue(postgresOptions0.testCollations);
    }

    @Test
    public void test2() throws Throwable {
        PostgresOptions postgresOptions0 = new PostgresOptions();
        LinkedList<PostgresOracleFactory> linkedList0 = new LinkedList<PostgresOracleFactory>();
        postgresOptions0.oracle = (List<PostgresOracleFactory>) linkedList0;
        PostgresOracleFactory postgresOracleFactory0 = PostgresOracleFactory.HAVING;
        linkedList0.add(postgresOracleFactory0);
        postgresOptions0.getTestOracleFactory();
        assertTrue(postgresOptions0.testCollations);
    }
}
