/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 11 21:48:45 GMT 2025
 */

package sqlancer.evosuite.clickhouse;

import static org.junit.jupiter.api.Assertions.*;
import java.util.LinkedList;
import java.util.List;
import org.junit.jupiter.api.Test;
import sqlancer.clickhouse.ClickHouseOptions;
import sqlancer.clickhouse.ClickHouseOracleFactory;

public class ClickHouseOptions_ESTest {

    @Test
    public void test0() throws Throwable {
        ClickHouseOptions clickHouseOptions0 = new ClickHouseOptions();
        LinkedList<ClickHouseOracleFactory> linkedList0 = new LinkedList<ClickHouseOracleFactory>();
        clickHouseOptions0.oracle = (List<ClickHouseOracleFactory>) linkedList0;
        clickHouseOptions0.oracle = null;
        clickHouseOptions0.getTestOracleFactory();
        assertTrue(clickHouseOptions0.enableAnalyzer);
        assertTrue(clickHouseOptions0.testJoins);
    }

    @Test
    public void test1() throws Throwable {
        ClickHouseOptions clickHouseOptions0 = new ClickHouseOptions();
        LinkedList<ClickHouseOracleFactory> linkedList0 = new LinkedList<ClickHouseOracleFactory>();
        clickHouseOptions0.oracle = (List<ClickHouseOracleFactory>) linkedList0;
        clickHouseOptions0.getTestOracleFactory();
        assertTrue(clickHouseOptions0.enableAnalyzer);
        assertTrue(clickHouseOptions0.testJoins);
    }

    @Test
    public void test2() throws Throwable {
        ClickHouseOptions clickHouseOptions0 = new ClickHouseOptions();
        LinkedList<ClickHouseOracleFactory> linkedList0 = new LinkedList<ClickHouseOracleFactory>();
        ClickHouseOracleFactory clickHouseOracleFactory0 = ClickHouseOracleFactory.TLPAggregate;
        linkedList0.offerLast(clickHouseOracleFactory0);
        clickHouseOptions0.oracle = (List<ClickHouseOracleFactory>) linkedList0;
        clickHouseOptions0.getTestOracleFactory();
        assertTrue(clickHouseOptions0.enableAnalyzer);
        assertTrue(clickHouseOptions0.testJoins);
    }
}
