/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 11 20:19:30 GMT 2025
 */

package sqlancer.evosuite.h2.ast;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;
import sqlancer.h2.ast.H2Constant;
import sqlancer.h2.ast.H2UnaryPostfixOperation;
import sqlancer.h2.H2ExpressionGenerator;

public class H2UnaryPostfixOperation_ESTest {

    @Test
    public void test0() throws Throwable {
        H2Constant.H2StringConstant h2Constant_H2StringConstant0 = new H2Constant.H2StringConstant(
                "sqlancer.h2.ast.H2UnaryPostfixOperation");
        H2ExpressionGenerator.H2BinaryArithmeticOperator h2ExpressionGenerator_H2BinaryArithmeticOperator0 = H2ExpressionGenerator.H2BinaryArithmeticOperator.MOD;
        H2UnaryPostfixOperation h2UnaryPostfixOperation0 = new H2UnaryPostfixOperation(h2Constant_H2StringConstant0,
                h2ExpressionGenerator_H2BinaryArithmeticOperator0);
    }
}
