/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 11 15:47:33 GMT 2025
 */

package sqlancer.evosuite.duckdb.ast;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;
import sqlancer.duckdb.ast.DuckDBConstant;
import sqlancer.duckdb.ast.DuckDBPostFixText;

public class DuckDBPostFixText_ESTest {

    @Test
    public void test0() throws Throwable {
        DuckDBConstant.DuckDBTextConstant duckDBConstant_DuckDBTextConstant0 = new DuckDBConstant.DuckDBTextConstant(
                "5");
        DuckDBPostFixText duckDBPostFixText0 = new DuckDBPostFixText(duckDBConstant_DuckDBTextConstant0, "SIN");
        assertEquals("SIN", duckDBPostFixText0.getText());
    }
}
