/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 11 16:17:06 GMT 2025
 */

package sqlancer.evosuite.duckdb.ast;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;
import sqlancer.duckdb.ast.DuckDBColumnReference;
import sqlancer.duckdb.DuckDBSchema;

public class DuckDBColumnReference_ESTest {

    @Test
    public void test0() throws Throwable {
        DuckDBSchema.DuckDBColumn duckDBSchema_DuckDBColumn0 = new DuckDBSchema.DuckDBColumn("",
                (DuckDBSchema.DuckDBCompositeDataType) null, false, false);
        DuckDBColumnReference duckDBColumnReference0 = new DuckDBColumnReference(duckDBSchema_DuckDBColumn0);
    }
}
