/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 11 17:50:32 GMT 2025
 */

package sqlancer.evosuite.duckdb.ast;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Collection;
import java.util.LinkedList;
import java.util.List;
import org.junit.jupiter.api.Test;
import sqlancer.duckdb.ast.DuckDBCaseOperator;
import sqlancer.duckdb.ast.DuckDBConstant;
import sqlancer.duckdb.ast.DuckDBExpression;
import sqlancer.duckdb.ast.DuckDBSelect;

public class DuckDBCaseOperator_ESTest {

    private void verifyException(String s, Exception e) {
    }

    @Test
    public void test0() throws Throwable {
        DuckDBExpression duckDBExpression0 = DuckDBConstant.createBooleanConstant(false);
        LinkedList<DuckDBConstant.DuckDBDateConstant> linkedList0 = new LinkedList<DuckDBConstant.DuckDBDateConstant>();
        List<DuckDBExpression> list0 = List.copyOf((Collection<? extends DuckDBExpression>) linkedList0);
        List<DuckDBExpression> list1 = List.of(duckDBExpression0);
        DuckDBConstant.DuckDBDoubleConstant duckDBConstant_DuckDBDoubleConstant0 = new DuckDBConstant.DuckDBDoubleConstant(
                503.7);
        DuckDBCaseOperator duckDBCaseOperator0 = null;
        try {
            duckDBCaseOperator0 = new DuckDBCaseOperator(duckDBExpression0, list1, list0,
                    duckDBConstant_DuckDBDoubleConstant0);
            fail("Expecting exception: IllegalArgumentException");

        } catch (IllegalArgumentException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.common.ast.newast.NewCaseOperatorNode", e);
        }
    }

    @Test
    public void test1() throws Throwable {
        DuckDBConstant.DuckDBTextConstant duckDBConstant_DuckDBTextConstant0 = new DuckDBConstant.DuckDBTextConstant(
                "A*FsYjqq");
        DuckDBSelect duckDBSelect0 = new DuckDBSelect();
        List<DuckDBExpression> list0 = duckDBSelect0.getGroupByClause();
        DuckDBCaseOperator duckDBCaseOperator0 = new DuckDBCaseOperator(duckDBConstant_DuckDBTextConstant0, list0,
                list0, duckDBSelect0);
    }
}
