/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 11 15:30:39 GMT 2025
 */

package sqlancer.evosuite.yugabyte.ycql.ast;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;
import sqlancer.h2.H2ExpressionGenerator;
import sqlancer.yugabyte.ycql.ast.YCQLConstant;
import sqlancer.yugabyte.ycql.ast.YCQLExpression;
import sqlancer.yugabyte.ycql.ast.YCQLUnaryPrefixOperation;

public class YCQLUnaryPrefixOperation_ESTest {

    @Test
    public void test0() throws Throwable {
        YCQLExpression yCQLExpression0 = YCQLConstant.createBooleanConstant(true);
        H2ExpressionGenerator.H2BinaryArithmeticOperator h2ExpressionGenerator_H2BinaryArithmeticOperator0 = H2ExpressionGenerator.H2BinaryArithmeticOperator.DIV;
        YCQLUnaryPrefixOperation yCQLUnaryPrefixOperation0 = new YCQLUnaryPrefixOperation(yCQLExpression0,
                h2ExpressionGenerator_H2BinaryArithmeticOperator0);
    }
}
