/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 12 01:30:39 GMT 2025
 */

package sqlancer.evosuite.cockroachdb.oracle.tlp;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

import sqlancer.cockroachdb.CockroachDBProvider;
import sqlancer.cockroachdb.oracle.tlp.CockroachDBTLPHavingOracle;

public class CockroachDBTLPHavingOracle_ESTest {

    private void verifyException(String s, Exception e) {
    }

    @Test
    public void test0() throws Throwable {
        CockroachDBProvider.CockroachDBGlobalState cockroachDBProvider_CockroachDBGlobalState0 = new CockroachDBProvider.CockroachDBGlobalState();
        CockroachDBTLPHavingOracle cockroachDBTLPHavingOracle0 = new CockroachDBTLPHavingOracle(
                cockroachDBProvider_CockroachDBGlobalState0);
        // Undeclared exception!
        try {
            cockroachDBTLPHavingOracle0.check();
            fail("Expecting exception: AssertionError");

        } catch (AssertionError e) {
            //
            // null
            //
        }
    }

    @Test
    public void test1() throws Throwable {
        CockroachDBProvider.CockroachDBGlobalState cockroachDBProvider_CockroachDBGlobalState0 = new CockroachDBProvider.CockroachDBGlobalState();
        CockroachDBTLPHavingOracle cockroachDBTLPHavingOracle0 = new CockroachDBTLPHavingOracle(
                cockroachDBProvider_CockroachDBGlobalState0);
        // Undeclared exception!
        try {
            cockroachDBTLPHavingOracle0.generatePredicate();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.cockroachdb.oracle.tlp.CockroachDBTLPHavingOracle", e);
        }
    }

    @Test
    public void test2() throws Throwable {
        CockroachDBProvider.CockroachDBGlobalState cockroachDBProvider_CockroachDBGlobalState0 = new CockroachDBProvider.CockroachDBGlobalState();
        CockroachDBTLPHavingOracle cockroachDBTLPHavingOracle0 = new CockroachDBTLPHavingOracle(
                cockroachDBProvider_CockroachDBGlobalState0);
        String string0 = cockroachDBTLPHavingOracle0.getLastQueryString();
        assertNull(string0);
    }

    @Test
    public void test3() throws Throwable {
        CockroachDBTLPHavingOracle cockroachDBTLPHavingOracle0 = new CockroachDBTLPHavingOracle(
                (CockroachDBProvider.CockroachDBGlobalState) null);
        // Undeclared exception!
        try {
            cockroachDBTLPHavingOracle0.check();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.cockroachdb.oracle.tlp.CockroachDBTLPBase", e);
        }
    }
}
