/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 11 19:06:39 GMT 2025
 */

package sqlancer.evosuite.presto.test;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;
import sqlancer.presto.PrestoGlobalState;
import sqlancer.presto.test.PrestoQueryPartitioningDistinctTester;

public class PrestoQueryPartitioningDistinctTester_ESTest {

    private void verifyException(String s, Exception e) {
    }

    @Test
    public void test0() throws Throwable {
        PrestoGlobalState prestoGlobalState0 = new PrestoGlobalState();
        PrestoQueryPartitioningDistinctTester prestoQueryPartitioningDistinctTester0 = new PrestoQueryPartitioningDistinctTester(
                prestoGlobalState0);
        // Undeclared exception!
        try {
            prestoQueryPartitioningDistinctTester0.check();
            fail("Expecting exception: AssertionError");

        } catch (AssertionError e) {
            //
            // null
            //
        }
    }

    @Test
    public void test1() throws Throwable {
        PrestoQueryPartitioningDistinctTester prestoQueryPartitioningDistinctTester0 = new PrestoQueryPartitioningDistinctTester(
                (PrestoGlobalState) null);
        // Undeclared exception!
        try {
            prestoQueryPartitioningDistinctTester0.check();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.presto.test.PrestoQueryPartitioningBase", e);
        }
    }
}
