/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 11 17:09:40 GMT 2025
 */

package sqlancer.evosuite.presto.test;

import static org.junit.jupiter.api.Assertions.*;
import java.util.LinkedList;
import org.junit.jupiter.api.Test;
import sqlancer.presto.PrestoGlobalState;
import sqlancer.presto.PrestoSchema;
import sqlancer.presto.test.PrestoQueryPartitioningGroupByTester;

public class PrestoQueryPartitioningGroupByTester_ESTest {

    private void verifyException(String s, Exception e) {
    }

    @Test
    public void test0() throws Throwable {
        PrestoGlobalState prestoGlobalState0 = new PrestoGlobalState();
        PrestoQueryPartitioningGroupByTester prestoQueryPartitioningGroupByTester0 = new PrestoQueryPartitioningGroupByTester(
                prestoGlobalState0);
        LinkedList<PrestoSchema.PrestoTable> linkedList0 = new LinkedList<PrestoSchema.PrestoTable>();
        PrestoSchema.PrestoTables prestoSchema_PrestoTables0 = new PrestoSchema.PrestoTables(linkedList0);
        prestoQueryPartitioningGroupByTester0.targetTables = prestoSchema_PrestoTables0;
        // Undeclared exception!
        try {
            prestoQueryPartitioningGroupByTester0.generateFetchColumns();
            fail("Expecting exception: AssertionError");

        } catch (AssertionError e) {
            //
            // [] 1
            //
        }
    }

    @Test
    public void test1() throws Throwable {
        PrestoGlobalState prestoGlobalState0 = new PrestoGlobalState();
        PrestoQueryPartitioningGroupByTester prestoQueryPartitioningGroupByTester0 = new PrestoQueryPartitioningGroupByTester(
                prestoGlobalState0);
        // Undeclared exception!
        try {
            prestoQueryPartitioningGroupByTester0.check();
            fail("Expecting exception: AssertionError");

        } catch (AssertionError e) {
            //
            // null
            //
        }
    }

    @Test
    public void test2() throws Throwable {
        PrestoQueryPartitioningGroupByTester prestoQueryPartitioningGroupByTester0 = new PrestoQueryPartitioningGroupByTester(
                (PrestoGlobalState) null);
        // Undeclared exception!
        try {
            prestoQueryPartitioningGroupByTester0.generateFetchColumns();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.presto.test.PrestoQueryPartitioningGroupByTester", e);
        }
    }

    @Test
    public void test3() throws Throwable {
        PrestoQueryPartitioningGroupByTester prestoQueryPartitioningGroupByTester0 = new PrestoQueryPartitioningGroupByTester(
                (PrestoGlobalState) null);
        // Undeclared exception!
        try {
            prestoQueryPartitioningGroupByTester0.check();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.presto.test.PrestoQueryPartitioningBase", e);
        }
    }
}
