/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 12 02:46:41 GMT 2025
 */

package sqlancer.evosuite.doris.ast;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;
import sqlancer.doris.ast.DorisBinaryArithmeticOperation;
import sqlancer.doris.ast.DorisColumnValue;
import sqlancer.doris.ast.DorisConstant;
import sqlancer.doris.ast.DorisExpression;
import sqlancer.doris.ast.DorisUnaryPrefixOperation;
import sqlancer.doris.DorisSchema;

public class DorisUnaryPrefixOperation_ESTest {

    private void verifyException(String s, Exception e) {
    }

    @Test
    public void test00() throws Throwable {
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation((DorisExpression) null,
                (DorisUnaryPrefixOperation.DorisUnaryPrefixOperator) null);
        dorisUnaryPrefixOperation0.getOp();
    }

    @Test
    public void test01() throws Throwable {
        DorisConstant dorisConstant0 = DorisConstant.createIntConstant(3792L);
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.NOT;
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation(dorisConstant0,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        DorisConstant.DorisIntConstant dorisConstant_DorisIntConstant0 = (DorisConstant.DorisIntConstant) dorisUnaryPrefixOperation0
                .getExpression();
        assertEquals(3792L, dorisConstant_DorisIntConstant0.asInt());
    }

    @Test
    public void test02() throws Throwable {
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.UNARY_PLUS;
        DorisConstant.DorisTextConstant dorisConstant_DorisTextConstant0 = new DorisConstant.DorisTextConstant("NOT");
        DorisColumnValue dorisColumnValue0 = DorisColumnValue.create((DorisSchema.DorisColumn) null,
                dorisConstant_DorisTextConstant0);
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation(dorisColumnValue0,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        DorisConstant dorisConstant0 = dorisUnaryPrefixOperation0.getExpectedValue();
        assertFalse(dorisConstant0.isInt());
    }

    @Test
    public void test03() throws Throwable {
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.UNARY_PLUS;
        DorisConstant dorisConstant0 = DorisConstant.createDatetimeConstant();
        DorisColumnValue dorisColumnValue0 = new DorisColumnValue((DorisSchema.DorisColumn) null, dorisConstant0);
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation(dorisColumnValue0,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        DorisConstant dorisConstant1 = dorisUnaryPrefixOperation0.getExpectedValue();
        assertEquals("CURRENT_TIMESTAMP", dorisConstant1.asString());
    }

    @Test
    public void test04() throws Throwable {
        DorisSchema.DorisColumnAggrType dorisSchema_DorisColumnAggrType0 = DorisSchema.DorisColumnAggrType.REPLACE;
        DorisSchema.DorisDataType dorisSchema_DorisDataType0 = DorisSchema.DorisDataType.VARCHAR;
        DorisSchema.DorisCompositeDataType dorisSchema_DorisCompositeDataType0 = new DorisSchema.DorisCompositeDataType(
                dorisSchema_DorisDataType0, 0);
        DorisSchema.DorisColumn dorisSchema_DorisColumn0 = new DorisSchema.DorisColumn("",
                dorisSchema_DorisCompositeDataType0, false, false, dorisSchema_DorisColumnAggrType0, false,
                "Y?iK14 dsI4|v8Zk");
        DorisConstant.DorisDateConstant dorisConstant_DorisDateConstant0 = new DorisConstant.DorisDateConstant(
                (String) null);
        DorisColumnValue dorisColumnValue0 = DorisColumnValue.create(dorisSchema_DorisColumn0,
                dorisConstant_DorisDateConstant0);
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.UNARY_PLUS;
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation(dorisColumnValue0,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        DorisConstant dorisConstant0 = dorisUnaryPrefixOperation0.getExpectedValue();
        assertFalse(dorisConstant0.isBoolean());
    }

    @Test
    public void test05() throws Throwable {
        DorisConstant.DorisBooleanConstant dorisConstant_DorisBooleanConstant0 = new DorisConstant.DorisBooleanConstant(
                true);
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.UNARY_MINUS;
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation(
                dorisConstant_DorisBooleanConstant0, dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        dorisUnaryPrefixOperation0.getExpectedType();
    }

    @Test
    public void test06() throws Throwable {
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.NOT;
        DorisConstant.DorisDatetimeConstant dorisConstant_DorisDatetimeConstant0 = new DorisConstant.DorisDatetimeConstant();
        DorisColumnValue dorisColumnValue0 = new DorisColumnValue((DorisSchema.DorisColumn) null,
                dorisConstant_DorisDatetimeConstant0);
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation(dorisColumnValue0,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        // Undeclared exception!
        try {
            dorisUnaryPrefixOperation0.getExpectedValue();
            fail("Expecting exception: UnsupportedOperationException");

        } catch (UnsupportedOperationException e) {
            //
            // sqlancer.doris.ast.DorisConstant$DorisNullConstant@0000000004
            //
            verifyException("sqlancer.doris.ast.DorisConstant", e);
        }
    }

    @Test
    public void test07() throws Throwable {
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.UNARY_MINUS;
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation((DorisExpression) null,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        // Undeclared exception!
        try {
            dorisUnaryPrefixOperation0.getExpectedValue();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.doris.ast.DorisUnaryPrefixOperation", e);
        }
    }

    @Test
    public void test08() throws Throwable {
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.UNARY_MINUS;
        DorisConstant.DorisDatetimeConstant dorisConstant_DorisDatetimeConstant0 = new DorisConstant.DorisDatetimeConstant();
        DorisColumnValue dorisColumnValue0 = new DorisColumnValue((DorisSchema.DorisColumn) null,
                dorisConstant_DorisDatetimeConstant0);
        DorisBinaryArithmeticOperation dorisBinaryArithmeticOperation0 = new DorisBinaryArithmeticOperation(
                dorisColumnValue0, dorisColumnValue0, dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation(
                dorisBinaryArithmeticOperation0, dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        // Undeclared exception!
        try {
            dorisUnaryPrefixOperation0.getExpectedValue();
            fail("Expecting exception: ClassCastException");

        } catch (ClassCastException e) {
            //
            // class sqlancer.doris.ast.DorisUnaryPrefixOperation$DorisUnaryPrefixOperator$3 cannot be cast to class
            // sqlancer.doris.ast.DorisBinaryArithmeticOperation$DorisBinaryArithmeticOperator
            // (sqlancer.doris.ast.DorisUnaryPrefixOperation$DorisUnaryPrefixOperator$3 and
            // sqlancer.doris.ast.DorisBinaryArithmeticOperation$DorisBinaryArithmeticOperator are in unnamed module of
            // loader org.evosuite.instrumentation.InstrumentingClassLoader @5c2a87e7)
            //
            verifyException("sqlancer.doris.ast.DorisBinaryArithmeticOperation", e);
        }
    }

    @Test
    public void test09() throws Throwable {
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.UNARY_MINUS;
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation((DorisExpression) null,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        // Undeclared exception!
        try {
            dorisUnaryPrefixOperation0.getExpectedType();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.doris.ast.DorisUnaryPrefixOperation$DorisUnaryPrefixOperator$3", e);
        }
    }

    @Test
    public void test10() throws Throwable {
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.NOT;
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation((DorisExpression) null,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator1 = dorisUnaryPrefixOperation0
                .getOp();
        assertSame(dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator1);
    }

    @Test
    public void test11() throws Throwable {
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.UNARY_MINUS;
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation((DorisExpression) null,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        DorisExpression dorisExpression0 = dorisUnaryPrefixOperation0.getExpression();
        assertNull(dorisExpression0);
    }

    @Test
    public void test12() throws Throwable {
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.UNARY_MINUS;
        DorisConstant.DorisFloatConstant dorisConstant_DorisFloatConstant0 = new DorisConstant.DorisFloatConstant(
                154.0);
        DorisColumnValue dorisColumnValue0 = DorisColumnValue.create((DorisSchema.DorisColumn) null,
                dorisConstant_DorisFloatConstant0);
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation(dorisColumnValue0,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        DorisConstant dorisConstant0 = dorisUnaryPrefixOperation0.getExpectedValue();
        assertNotSame(dorisConstant_DorisFloatConstant0, dorisConstant0);
    }

    @Test
    public void test13() throws Throwable {
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.UNARY_MINUS;
        DorisConstant dorisConstant0 = DorisConstant.createIntConstant((-1L));
        DorisColumnValue dorisColumnValue0 = new DorisColumnValue((DorisSchema.DorisColumn) null, dorisConstant0);
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation(dorisColumnValue0,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        DorisConstant dorisConstant1 = dorisUnaryPrefixOperation0.getExpectedValue();
        assertEquals(1L, dorisConstant1.asInt());
    }

    @Test
    public void test14() throws Throwable {
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.UNARY_MINUS;
        DorisConstant dorisConstant0 = DorisConstant.createNullConstant();
        DorisColumnValue dorisColumnValue0 = DorisColumnValue.create((DorisSchema.DorisColumn) null, dorisConstant0);
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation(dorisColumnValue0,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        DorisConstant dorisConstant1 = dorisUnaryPrefixOperation0.getExpectedValue();
        assertFalse(dorisConstant1.isNum());
    }

    @Test
    public void test15() throws Throwable {
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.UNARY_MINUS;
        DorisConstant dorisConstant0 = DorisConstant.createDatetimeConstant();
        DorisColumnValue dorisColumnValue0 = new DorisColumnValue((DorisSchema.DorisColumn) null, dorisConstant0);
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation(dorisColumnValue0,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        DorisConstant dorisConstant1 = dorisUnaryPrefixOperation0.getExpectedValue();
        assertNull(dorisConstant1);
    }

    @Test
    public void test16() throws Throwable {
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.NOT;
        DorisConstant.DorisBooleanConstant dorisConstant_DorisBooleanConstant0 = new DorisConstant.DorisBooleanConstant(
                false);
        DorisColumnValue dorisColumnValue0 = DorisColumnValue.create((DorisSchema.DorisColumn) null,
                dorisConstant_DorisBooleanConstant0);
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation(dorisColumnValue0,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        DorisConstant dorisConstant0 = dorisUnaryPrefixOperation0.getExpectedValue();
        assertEquals("true", dorisConstant0.toString());
        assertNotNull(dorisConstant0);
    }

    @Test
    public void test17() throws Throwable {
        DorisConstant dorisConstant0 = DorisConstant.createNullConstant();
        DorisColumnValue dorisColumnValue0 = new DorisColumnValue((DorisSchema.DorisColumn) null, dorisConstant0);
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.NOT;
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation(dorisColumnValue0,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        DorisConstant dorisConstant1 = dorisUnaryPrefixOperation0.getExpectedValue();
        assertFalse(dorisConstant1.isNum());
    }

    @Test
    public void test18() throws Throwable {
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.NOT;
        DorisConstant dorisConstant0 = DorisConstant.createBooleanConstant(true);
        DorisColumnValue dorisColumnValue0 = DorisColumnValue.create((DorisSchema.DorisColumn) null, dorisConstant0);
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation(dorisColumnValue0,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        DorisConstant dorisConstant1 = dorisUnaryPrefixOperation0.getExpectedValue();
        assertEquals("false", dorisConstant1.asString());
        assertNotNull(dorisConstant1);
    }

    @Test
    public void test19() throws Throwable {
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.UNARY_PLUS;
        DorisSchema.DorisDataType dorisSchema_DorisDataType0 = dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0
                .getRandomInputDataTypes();
        DorisConstant.DorisFloatConstant dorisConstant_DorisFloatConstant0 = new DorisConstant.DorisFloatConstant(
                (-1220.268097));
        DorisConstant dorisConstant0 = dorisConstant_DorisFloatConstant0.cast(dorisSchema_DorisDataType0);
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation(dorisConstant0,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        DorisConstant dorisConstant1 = dorisUnaryPrefixOperation0.getExpectedValue();
        assertNull(dorisConstant1);
    }

    @Test
    public void test20() throws Throwable {
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.NOT;
        String string0 = dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0.getTextRepresentation();
        assertEquals("NOT", string0);
    }

    @Test
    public void test21() throws Throwable {
        DorisConstant dorisConstant0 = DorisConstant.createIntConstant(0L);
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.UNARY_PLUS;
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation(dorisConstant0,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        DorisSchema.DorisDataType dorisSchema_DorisDataType0 = dorisUnaryPrefixOperation0.getExpectedType();
        assertEquals(DorisSchema.DorisDataType.INT, dorisSchema_DorisDataType0);
    }

    @Test
    public void test22() throws Throwable {
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.UNARY_MINUS;
        DorisConstant dorisConstant0 = DorisConstant.createIntConstant(0L);
        DorisSchema.DorisDataType dorisSchema_DorisDataType0 = dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0
                .getExpressionType(dorisConstant0);
        assertEquals(DorisSchema.DorisDataType.INT, dorisSchema_DorisDataType0);
    }

    @Test
    public void test23() throws Throwable {
        DorisUnaryPrefixOperation.DorisUnaryPrefixOperator dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0 = DorisUnaryPrefixOperation.DorisUnaryPrefixOperator.NOT;
        DorisUnaryPrefixOperation dorisUnaryPrefixOperation0 = new DorisUnaryPrefixOperation((DorisExpression) null,
                dorisUnaryPrefixOperation_DorisUnaryPrefixOperator0);
        DorisSchema.DorisDataType dorisSchema_DorisDataType0 = dorisUnaryPrefixOperation0.getExpectedType();
        assertEquals(DorisSchema.DorisDataType.BOOLEAN, dorisSchema_DorisDataType0);
    }
}
