/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 11 15:13:07 GMT 2025
 */

package sqlancer.evosuite.doris.oracle.tlp;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;
import sqlancer.doris.DorisProvider;
import sqlancer.doris.oracle.tlp.DorisQueryPartitioningAggregateTester;

public class DorisQueryPartitioningAggregateTester_ESTest {

    private void verifyException(String s, Exception e) {
    }

    @Test
    public void test0() throws Throwable {
        DorisProvider.DorisGlobalState dorisProvider_DorisGlobalState0 = new DorisProvider.DorisGlobalState();
        DorisQueryPartitioningAggregateTester dorisQueryPartitioningAggregateTester0 = new DorisQueryPartitioningAggregateTester(
                dorisProvider_DorisGlobalState0);
        // Undeclared exception!
        try {
            dorisQueryPartitioningAggregateTester0.check();
            fail("Expecting exception: AssertionError");

        } catch (AssertionError e) {
            //
            // null
            //
        }
    }

    @Test
    public void test1() throws Throwable {
        DorisQueryPartitioningAggregateTester dorisQueryPartitioningAggregateTester0 = new DorisQueryPartitioningAggregateTester(
                (DorisProvider.DorisGlobalState) null);
        // Undeclared exception!
        try {
            dorisQueryPartitioningAggregateTester0.check();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.doris.oracle.tlp.DorisQueryPartitioningBase", e);
        }
    }
}
