/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 11 23:09:32 GMT 2025
 */

package sqlancer.evosuite.cnosdb.ast;

import static org.junit.jupiter.api.Assertions.*;

import java.util.List;

import org.junit.jupiter.api.Test;

import sqlancer.cnosdb.ast.CnosDBAggregate;
import sqlancer.cnosdb.CnosDBSchema;

public class CnosDBAggregate_ESTest {

    @Test
    public void test00() throws Throwable {
        CnosDBAggregate.CnosDBAggregateFunction cnosDBAggregate_CnosDBAggregateFunction0 = CnosDBAggregate.CnosDBAggregateFunction.COVAR;
        CnosDBSchema.CnosDBDataType cnosDBSchema_CnosDBDataType0 = CnosDBSchema.CnosDBDataType.STRING;
        boolean boolean0 = cnosDBAggregate_CnosDBAggregateFunction0.supportsReturnType(cnosDBSchema_CnosDBDataType0);
        assertFalse(boolean0);
    }

    @Test
    public void test01() throws Throwable {
        CnosDBAggregate.CnosDBAggregateFunction cnosDBAggregate_CnosDBAggregateFunction0 = CnosDBAggregate.CnosDBAggregateFunction.CORR;
        CnosDBSchema.CnosDBDataType cnosDBSchema_CnosDBDataType0 = cnosDBAggregate_CnosDBAggregateFunction0
                .getRandomReturnType();
        assertEquals(CnosDBSchema.CnosDBDataType.DOUBLE, cnosDBSchema_CnosDBDataType0);
    }

    @Test
    public void test02() throws Throwable {
        CnosDBAggregate.CnosDBAggregateFunction cnosDBAggregate_CnosDBAggregateFunction0 = CnosDBAggregate.CnosDBAggregateFunction.COUNT;
        CnosDBSchema.CnosDBDataType cnosDBSchema_CnosDBDataType0 = CnosDBSchema.CnosDBDataType.STRING;
        CnosDBSchema.CnosDBDataType[] cnosDBSchema_CnosDBDataTypeArray0 = cnosDBAggregate_CnosDBAggregateFunction0
                .getArgsTypes(cnosDBSchema_CnosDBDataType0);
        assertEquals(1, cnosDBSchema_CnosDBDataTypeArray0.length);
    }

    @Test
    public void test03() throws Throwable {
        CnosDBAggregate.CnosDBAggregateFunction cnosDBAggregate_CnosDBAggregateFunction0 = CnosDBAggregate.CnosDBAggregateFunction.COVAR_SAMP;
        CnosDBSchema.CnosDBDataType cnosDBSchema_CnosDBDataType0 = CnosDBSchema.CnosDBDataType.TIMESTAMP;
        CnosDBSchema.CnosDBDataType[] cnosDBSchema_CnosDBDataTypeArray0 = cnosDBAggregate_CnosDBAggregateFunction0
                .getArgsTypes(cnosDBSchema_CnosDBDataType0);
        assertEquals(2, cnosDBSchema_CnosDBDataTypeArray0.length);
    }

    @Test
    public void test04() throws Throwable {
        CnosDBAggregate.CnosDBAggregateFunction cnosDBAggregate_CnosDBAggregateFunction0 = CnosDBAggregate.CnosDBAggregateFunction.COVAR;
        CnosDBSchema.CnosDBDataType cnosDBSchema_CnosDBDataType0 = CnosDBSchema.CnosDBDataType.STRING;
        CnosDBSchema.CnosDBDataType[] cnosDBSchema_CnosDBDataTypeArray0 = cnosDBAggregate_CnosDBAggregateFunction0
                .getArgsTypes(cnosDBSchema_CnosDBDataType0);
        assertEquals(2, cnosDBSchema_CnosDBDataTypeArray0.length);
    }

    @Test
    public void test05() throws Throwable {
        CnosDBAggregate.CnosDBAggregateFunction cnosDBAggregate_CnosDBAggregateFunction0 = CnosDBAggregate.CnosDBAggregateFunction.COVAR_POP;
        CnosDBSchema.CnosDBDataType cnosDBSchema_CnosDBDataType0 = CnosDBSchema.CnosDBDataType.TIMESTAMP;
        CnosDBSchema.CnosDBDataType[] cnosDBSchema_CnosDBDataTypeArray0 = cnosDBAggregate_CnosDBAggregateFunction0
                .getArgsTypes(cnosDBSchema_CnosDBDataType0);
        assertEquals(2, cnosDBSchema_CnosDBDataTypeArray0.length);
    }

    // @Test
    // public void test06() throws Throwable {
    // CnosDBAggregate.CnosDBAggregateFunction cnosDBAggregate_CnosDBAggregateFunction0 =
    // CnosDBAggregate.CnosDBAggregateFunction.GROUPING;
    // CnosDBSelect cnosDBSelect0 = new CnosDBSelect();
    // List<CnosDBExpression> list0 = cnosDBSelect0.getJoinList();
    // CnosDBAggregate cnosDBAggregate0 = new CnosDBAggregate(list0, cnosDBAggregate_CnosDBAggregateFunction0);
    // }

    @Test
    public void test07() throws Throwable {
        CnosDBSchema.CnosDBDataType cnosDBSchema_CnosDBDataType0 = CnosDBSchema.CnosDBDataType.TIMESTAMP;
        CnosDBAggregate.CnosDBAggregateFunction cnosDBAggregate_CnosDBAggregateFunction0 = CnosDBAggregate.CnosDBAggregateFunction.CORR;
        CnosDBSchema.CnosDBDataType[] cnosDBSchema_CnosDBDataTypeArray0 = cnosDBAggregate_CnosDBAggregateFunction0
                .getArgsTypes(cnosDBSchema_CnosDBDataType0);
        assertEquals(2, cnosDBSchema_CnosDBDataTypeArray0.length);
    }

    @Test
    public void test08() throws Throwable {
        CnosDBAggregate.CnosDBAggregateFunction cnosDBAggregate_CnosDBAggregateFunction0 = CnosDBAggregate.CnosDBAggregateFunction.APPROX_PERCENTILE_CONT_WITH_WEIGHT;
        CnosDBSchema.CnosDBDataType cnosDBSchema_CnosDBDataType0 = CnosDBSchema.CnosDBDataType.TIMESTAMP;
        CnosDBSchema.CnosDBDataType[] cnosDBSchema_CnosDBDataTypeArray0 = cnosDBAggregate_CnosDBAggregateFunction0
                .getArgsTypes(cnosDBSchema_CnosDBDataType0);
        assertEquals(3, cnosDBSchema_CnosDBDataTypeArray0.length);
    }

    @Test
    public void test09() throws Throwable {
        CnosDBAggregate.CnosDBAggregateFunction cnosDBAggregate_CnosDBAggregateFunction0 = CnosDBAggregate.CnosDBAggregateFunction.APPROX_PERCENTILE_CONT;
        CnosDBSchema.CnosDBDataType cnosDBSchema_CnosDBDataType0 = CnosDBSchema.CnosDBDataType.TIMESTAMP;
        CnosDBSchema.CnosDBDataType[] cnosDBSchema_CnosDBDataTypeArray0 = cnosDBAggregate_CnosDBAggregateFunction0
                .getArgsTypes(cnosDBSchema_CnosDBDataType0);
        assertEquals(2, cnosDBSchema_CnosDBDataTypeArray0.length);
    }

    @Test
    public void test10() throws Throwable {
        CnosDBAggregate.CnosDBAggregateFunction cnosDBAggregate_CnosDBAggregateFunction0 = CnosDBAggregate.CnosDBAggregateFunction.APPROX_MEDIAN;
        CnosDBSchema.CnosDBDataType cnosDBSchema_CnosDBDataType0 = CnosDBSchema.CnosDBDataType.UINT;
        CnosDBSchema.CnosDBDataType[] cnosDBSchema_CnosDBDataTypeArray0 = cnosDBAggregate_CnosDBAggregateFunction0
                .getArgsTypes(cnosDBSchema_CnosDBDataType0);
        assertEquals(1, cnosDBSchema_CnosDBDataTypeArray0.length);
    }

    @Test
    public void test11() throws Throwable {
        CnosDBSchema.CnosDBDataType cnosDBSchema_CnosDBDataType0 = CnosDBSchema.CnosDBDataType.TIMESTAMP;
        List<CnosDBAggregate.CnosDBAggregateFunction> list0 = CnosDBAggregate.CnosDBAggregateFunction
                .getAggregates(cnosDBSchema_CnosDBDataType0);
        assertEquals(2, list0.size());
    }
}
