/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 11 18:50:15 GMT 2025
 */

package sqlancer.evosuite.presto.ast;

import sqlancer.presto.ast.PrestoMultiValuedComparisonType;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

public class PrestoMultiValuedComparisonType_ESTest {

    @Test
    public void test0() throws Throwable {
        PrestoMultiValuedComparisonType[] prestoMultiValuedComparisonTypeArray0 = PrestoMultiValuedComparisonType
                .values();
        assertEquals(3, prestoMultiValuedComparisonTypeArray0.length);
    }

    @Test
    public void test1() throws Throwable {
        PrestoMultiValuedComparisonType prestoMultiValuedComparisonType0 = PrestoMultiValuedComparisonType
                .valueOf("ANY");
        assertEquals(PrestoMultiValuedComparisonType.ANY, prestoMultiValuedComparisonType0);
    }

    @Test
    public void test2() throws Throwable {
        PrestoMultiValuedComparisonType prestoMultiValuedComparisonType0 = PrestoMultiValuedComparisonType.getRandom();
        assertEquals(PrestoMultiValuedComparisonType.ANY, prestoMultiValuedComparisonType0);
    }
}
