/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 11 18:27:45 GMT 2025
 */

package sqlancer.evosuite.yugabyte.ysql.ast;

import static org.junit.jupiter.api.Assertions.*;
import java.math.BigDecimal;
import org.junit.jupiter.api.Test;
import sqlancer.yugabyte.ysql.ast.YSQLColumnValue;
import sqlancer.yugabyte.ysql.ast.YSQLConstant;
import sqlancer.yugabyte.ysql.ast.YSQLExpression;
import sqlancer.yugabyte.ysql.ast.YSQLPostfixOperation;
import sqlancer.yugabyte.ysql.ast.YSQLPostfixText;
import sqlancer.yugabyte.ysql.ast.YSQLSelect;
import sqlancer.yugabyte.ysql.YSQLSchema;

public class YSQLPostfixText_ESTest {

    @Test
    public void test00() throws Throwable {
        YSQLSchema.YSQLColumn ySQLSchema_YSQLColumn0 = YSQLSchema.YSQLColumn.createDummy("/c!^shGe4)YgLt|l\"0");
        YSQLColumnValue ySQLColumnValue0 = YSQLColumnValue.create(ySQLSchema_YSQLColumn0, (YSQLConstant) null);
        YSQLSchema.YSQLDataType ySQLSchema_YSQLDataType0 = YSQLSchema.YSQLDataType.REAL;
        YSQLPostfixText ySQLPostfixText0 = new YSQLPostfixText(ySQLColumnValue0, (String) null, (YSQLConstant) null,
                ySQLSchema_YSQLDataType0);
        String string0 = ySQLPostfixText0.getText();
        assertNull(string0);
    }

    @Test
    public void test01() throws Throwable {
        YSQLSelect ySQLSelect0 = new YSQLSelect();
        BigDecimal bigDecimal0 = BigDecimal.ZERO;
        YSQLConstant ySQLConstant0 = YSQLConstant.createDecimalConstant(bigDecimal0);
        YSQLSchema.YSQLDataType ySQLSchema_YSQLDataType0 = YSQLSchema.YSQLDataType.REAL;
        YSQLPostfixText ySQLPostfixText0 = new YSQLPostfixText(ySQLSelect0, "", ySQLConstant0,
                ySQLSchema_YSQLDataType0);
        String string0 = ySQLPostfixText0.getText();
        assertEquals("", string0);
    }

    @Test
    public void test02() throws Throwable {
        YSQLConstant.YSQLNullConstant ySQLConstant_YSQLNullConstant0 = new YSQLConstant.YSQLNullConstant();
        YSQLSchema.YSQLDataType ySQLSchema_YSQLDataType0 = YSQLSchema.YSQLDataType.TEXT;
        YSQLPostfixText ySQLPostfixText0 = new YSQLPostfixText(ySQLConstant_YSQLNullConstant0, "+Inf",
                ySQLConstant_YSQLNullConstant0, ySQLSchema_YSQLDataType0);
        YSQLSchema.YSQLDataType ySQLSchema_YSQLDataType1 = ySQLPostfixText0.getExpressionType();
        assertSame(ySQLSchema_YSQLDataType1, ySQLSchema_YSQLDataType0);
    }

    @Test
    public void test03() throws Throwable {
        YSQLSchema.YSQLDataType ySQLSchema_YSQLDataType0 = YSQLSchema.YSQLDataType.INT;
        YSQLPostfixText ySQLPostfixText0 = new YSQLPostfixText((YSQLExpression) null,
                "sqlancer.yugabyte.ysql.ast.YSQLPostfixText", (YSQLConstant) null, ySQLSchema_YSQLDataType0);
        YSQLExpression ySQLExpression0 = ySQLPostfixText0.getExpr();
        assertNull(ySQLExpression0);
    }

    @Test
    public void test04() throws Throwable {
        YSQLSchema.YSQLColumn ySQLSchema_YSQLColumn0 = YSQLSchema.YSQLColumn.createDummy("/c!^shGe4)YgLt|l\"0");
        YSQLColumnValue ySQLColumnValue0 = YSQLColumnValue.create(ySQLSchema_YSQLColumn0, (YSQLConstant) null);
        YSQLSchema.YSQLDataType ySQLSchema_YSQLDataType0 = YSQLSchema.YSQLDataType.REAL;
        YSQLPostfixText ySQLPostfixText0 = new YSQLPostfixText(ySQLColumnValue0, (String) null, (YSQLConstant) null,
                ySQLSchema_YSQLDataType0);
        YSQLConstant ySQLConstant0 = ySQLPostfixText0.getExpectedValue();
        assertNull(ySQLConstant0);
    }

    @Test
    public void test05() throws Throwable {
        YSQLConstant.StringConstant ySQLConstant_StringConstant0 = new YSQLConstant.StringConstant("");
        YSQLSchema.YSQLDataType ySQLSchema_YSQLDataType0 = YSQLSchema.YSQLDataType.BYTEA;
        YSQLPostfixText ySQLPostfixText0 = new YSQLPostfixText(ySQLConstant_StringConstant0, "",
                ySQLConstant_StringConstant0, ySQLSchema_YSQLDataType0);
        YSQLConstant ySQLConstant0 = ySQLPostfixText0.getExpectedValue();
        assertFalse(ySQLConstant0.isNull());
    }

    @Test
    public void test06() throws Throwable {
        YSQLConstant.YSQLNullConstant ySQLConstant_YSQLNullConstant0 = new YSQLConstant.YSQLNullConstant();
        YSQLSchema.YSQLDataType ySQLSchema_YSQLDataType0 = YSQLSchema.YSQLDataType.TEXT;
        YSQLPostfixText ySQLPostfixText0 = new YSQLPostfixText(ySQLConstant_YSQLNullConstant0, "+Inf",
                ySQLConstant_YSQLNullConstant0, ySQLSchema_YSQLDataType0);
        YSQLConstant ySQLConstant0 = ySQLPostfixText0.getExpectedValue();
        assertEquals("NULL", ySQLConstant0.getUnquotedTextRepresentation());
    }

    @Test
    public void test07() throws Throwable {
        YSQLConstant.IntConstant ySQLConstant_IntConstant0 = new YSQLConstant.IntConstant(3188L);
        YSQLConstant ySQLConstant0 = YSQLConstant.createByteConstant("k%)WV7h0_wZV>DHCw,");
        YSQLPostfixOperation.PostfixOperator ySQLPostfixOperation_PostfixOperator0 = YSQLPostfixOperation.PostfixOperator.IS_NOT_UNKNOWN;
        YSQLPostfixOperation ySQLPostfixOperation0 = new YSQLPostfixOperation(ySQLConstant0,
                ySQLPostfixOperation_PostfixOperator0);
        YSQLConstant ySQLConstant1 = ySQLPostfixOperation0.getExpectedValue();
        YSQLSchema.YSQLDataType ySQLSchema_YSQLDataType0 = YSQLSchema.YSQLDataType.FLOAT;
        YSQLPostfixText ySQLPostfixText0 = new YSQLPostfixText(ySQLConstant_IntConstant0, "k%)WV7h0_wZV>DHCw,",
                ySQLConstant1, ySQLSchema_YSQLDataType0);
        YSQLConstant ySQLConstant2 = ySQLPostfixText0.getExpectedValue();
        assertSame(ySQLConstant1, ySQLConstant2);
    }

    @Test
    public void test08() throws Throwable {
        YSQLConstant.IntConstant ySQLConstant_IntConstant0 = new YSQLConstant.IntConstant(0L);
        YSQLConstant ySQLConstant0 = ySQLConstant_IntConstant0.isEquals(ySQLConstant_IntConstant0);
        YSQLSchema.YSQLDataType ySQLSchema_YSQLDataType0 = YSQLSchema.YSQLDataType.DECIMAL;
        YSQLPostfixText ySQLPostfixText0 = new YSQLPostfixText(ySQLConstant0, "g2+LD(MjY+", ySQLConstant_IntConstant0,
                ySQLSchema_YSQLDataType0);
        YSQLConstant ySQLConstant1 = ySQLPostfixText0.getExpectedValue();
        assertEquals("0", ySQLConstant1.getUnquotedTextRepresentation());
    }

    @Test
    public void test09() throws Throwable {
        YSQLConstant.IntConstant ySQLConstant_IntConstant0 = new YSQLConstant.IntConstant(0L);
        YSQLConstant ySQLConstant0 = ySQLConstant_IntConstant0.isEquals(ySQLConstant_IntConstant0);
        YSQLSchema.YSQLDataType ySQLSchema_YSQLDataType0 = YSQLSchema.YSQLDataType.DECIMAL;
        YSQLPostfixText ySQLPostfixText0 = new YSQLPostfixText(ySQLConstant0, "g2+LD(MjY+", ySQLConstant_IntConstant0,
                ySQLSchema_YSQLDataType0);
        YSQLConstant.BooleanConstant ySQLConstant_BooleanConstant0 = (YSQLConstant.BooleanConstant) ySQLPostfixText0
                .getExpr();
        assertFalse(ySQLConstant_BooleanConstant0.isInt());
    }

    @Test
    public void test10() throws Throwable {
        YSQLConstant.StringConstant ySQLConstant_StringConstant0 = new YSQLConstant.StringConstant("~P");
        YSQLSchema.YSQLDataType ySQLSchema_YSQLDataType0 = YSQLSchema.YSQLDataType.TEXT;
        YSQLPostfixText ySQLPostfixText0 = new YSQLPostfixText(ySQLConstant_StringConstant0, "~P",
                ySQLConstant_StringConstant0, ySQLSchema_YSQLDataType0);
        String string0 = ySQLPostfixText0.getText();
        assertEquals("~P", string0);
    }

    @Test
    public void test11() throws Throwable {
        YSQLConstant.ByteConstant ySQLConstant_ByteConstant0 = new YSQLConstant.ByteConstant("");
        YSQLPostfixText ySQLPostfixText0 = new YSQLPostfixText((YSQLExpression) null, "", ySQLConstant_ByteConstant0,
                (YSQLSchema.YSQLDataType) null);
        ySQLPostfixText0.getExpressionType();
    }
}
