/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 12 02:26:51 GMT 2025
 */

package sqlancer.evosuite.datafusion;

import static org.junit.jupiter.api.Assertions.*;

import java.nio.file.InvalidPathException;
import java.util.List;
import org.junit.jupiter.api.Test;
import sqlancer.citus.CitusGlobalState;
import sqlancer.datafusion.DataFusionProvider;
import sqlancer.datafusion.DataFusionUtil;

public class DataFusionUtil_ESTest {

    private void verifyException(String s, Exception e) {
    }

    @Test
    public void test01() throws Throwable {
        // Undeclared exception!
        try {
            DataFusionUtil.getReplay("/*DML*/");
            fail("Expecting exception: InvalidPathException");

        } catch (InvalidPathException e) {
        }
    }

    @Test
    public void test02() throws Throwable {
        DataFusionProvider.DataFusionGlobalState dataFusionProvider_DataFusionGlobalState0 = new DataFusionProvider.DataFusionGlobalState();
        // Undeclared exception!
        try {
            DataFusionUtil.displayTables(dataFusionProvider_DataFusionGlobalState0, (List<String>) null);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.datafusion.DataFusionUtil", e);
        }
    }

    @Test
    public void test03() throws Throwable {
        // Undeclared exception!
        try {
            DataFusionUtil.dfAssert(false, (String) null);
            fail("Expecting exception: AssertionError");

        } catch (AssertionError e) {
            //
            // null
            //
        }
    }

    @Test
    public void test04() throws Throwable {
        DataFusionProvider.DataFusionGlobalState dataFusionProvider_DataFusionGlobalState0 = new DataFusionProvider.DataFusionGlobalState();
        DataFusionUtil.DataFusionLogger.DataFusionLogType dataFusionUtil_DataFusionLogger_DataFusionLogType0 = DataFusionUtil.DataFusionLogger.DataFusionLogType.ERROR;
        dataFusionProvider_DataFusionGlobalState0.dfLogger
                .appendToLog(dataFusionUtil_DataFusionLogger_DataFusionLogType0, "");
        assertNull(dataFusionProvider_DataFusionGlobalState0.getDatabaseName());
    }

    @Test
    public void test05() throws Throwable {
        DataFusionProvider.DataFusionGlobalState dataFusionProvider_DataFusionGlobalState0 = new DataFusionProvider.DataFusionGlobalState();
        DataFusionUtil.DataFusionLogger.DataFusionLogType dataFusionUtil_DataFusionLogger_DataFusionLogType0 = DataFusionUtil.DataFusionLogger.DataFusionLogType.SELECT;
        // Undeclared exception!
        try {
            dataFusionProvider_DataFusionGlobalState0.dfLogger
                    .appendToLog(dataFusionUtil_DataFusionLogger_DataFusionLogType0, "O");
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.datafusion.DataFusionUtil$DataFusionLogger", e);
        }
    }

    @Test
    public void test06() throws Throwable {
        DataFusionUtil.DataFusionInstanceID dataFusionUtil_DataFusionInstanceID0 = new DataFusionUtil.DataFusionInstanceID(
                "tD 8e");
        DataFusionUtil.DataFusionLogger dataFusionUtil_DataFusionLogger0 = new DataFusionUtil.DataFusionLogger(
                (DataFusionProvider.DataFusionGlobalState) null, dataFusionUtil_DataFusionInstanceID0);
        DataFusionUtil.DataFusionLogger.DataFusionLogType dataFusionUtil_DataFusionLogger_DataFusionLogType0 = DataFusionUtil.DataFusionLogger.DataFusionLogType.DML;
        // Undeclared exception!
        try {
            dataFusionUtil_DataFusionLogger0.appendToLog(dataFusionUtil_DataFusionLogger_DataFusionLogType0,
                    "sqlancer.clickhouse.ClickHouseOracleFactory");
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.datafusion.DataFusionUtil$DataFusionLogger", e);
        }
    }

    @Test
    public void test08() throws Throwable {
        String string0 = DataFusionUtil.getReplay("QZd");
        assertEquals("", string0);
    }

    @Test
    public void test13() throws Throwable {
        DataFusionUtil.dfAssert(true, "QZd");
    }

    @Test
    public void test14() throws Throwable {
        DataFusionProvider.DataFusionGlobalState dataFusionProvider_DataFusionGlobalState0 = new DataFusionProvider.DataFusionGlobalState();
        CitusGlobalState citusGlobalState0 = new CitusGlobalState();
        List<String> list0 = citusGlobalState0.getCollates();
        String string0 = DataFusionUtil.displayTables(dataFusionProvider_DataFusionGlobalState0, list0);
        assertFalse(list0.contains(string0));
    }

    @Test
    public void test15() throws Throwable {
        DataFusionUtil.DataFusionInstanceID dataFusionUtil_DataFusionInstanceID0 = new DataFusionUtil.DataFusionInstanceID(
                "");
        String string0 = dataFusionUtil_DataFusionInstanceID0.toString();
        assertEquals("", string0);
    }

    @Test
    public void test16() throws Throwable {
        DataFusionProvider.DataFusionGlobalState dataFusionProvider_DataFusionGlobalState0 = new DataFusionProvider.DataFusionGlobalState();
        List<String> list0 = List.of("O", "O");
        // Undeclared exception!
        try {
            DataFusionUtil.displayTables(dataFusionProvider_DataFusionGlobalState0, list0);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.datafusion.DataFusionUtil", e);
        }
    }
}
