/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 11 16:41:41 GMT 2025
 */

package sqlancer.evosuite.common.oracle;

import org.junit.jupiter.api.Test;
import sqlancer.duckdb.DuckDBProvider;
import sqlancer.duckdb.test.DuckDBQueryPartitioningGroupByTester;

public class TernaryLogicPartitioningOracleBase_ESTest {

    @Test
    public void test0() throws Throwable {
        DuckDBProvider.DuckDBGlobalState duckDBProvider_DuckDBGlobalState0 = new DuckDBProvider.DuckDBGlobalState();
        DuckDBQueryPartitioningGroupByTester duckDBQueryPartitioningGroupByTester0 = new DuckDBQueryPartitioningGroupByTester(
                duckDBProvider_DuckDBGlobalState0);
    }
}
