/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 11 16:13:44 GMT 2025
 */

package sqlancer.evosuite.doris;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;
import sqlancer.common.oracle.TestOracle;
import sqlancer.doris.DorisOracleFactory;
import sqlancer.doris.DorisProvider;

public class DorisOracleFactory_ESTest {

    private void verifyException(String s, Exception e) {
    }

    @Test
    public void test0() throws Throwable {
        DorisOracleFactory dorisOracleFactory0 = DorisOracleFactory.PQS;
        DorisProvider.DorisGlobalState dorisProvider_DorisGlobalState0 = new DorisProvider.DorisGlobalState();
        TestOracle<DorisProvider.DorisGlobalState> testOracle0 = dorisOracleFactory0
                .create(dorisProvider_DorisGlobalState0);
        assertNotNull(testOracle0);
    }

    @Test
    public void test1() throws Throwable {
        DorisOracleFactory dorisOracleFactory0 = DorisOracleFactory.DISTINCT;
        DorisProvider.DorisGlobalState dorisProvider_DorisGlobalState0 = new DorisProvider.DorisGlobalState();
        TestOracle<DorisProvider.DorisGlobalState> testOracle0 = dorisOracleFactory0
                .create(dorisProvider_DorisGlobalState0);
        assertNotNull(testOracle0);
    }

    @Test
    public void test2() throws Throwable {
        DorisProvider.DorisGlobalState dorisProvider_DorisGlobalState0 = new DorisProvider.DorisGlobalState();
        DorisOracleFactory dorisOracleFactory0 = DorisOracleFactory.AGGREGATE;
        TestOracle<DorisProvider.DorisGlobalState> testOracle0 = dorisOracleFactory0
                .create(dorisProvider_DorisGlobalState0);
        assertNotNull(testOracle0);
    }

    @Test
    public void test3() throws Throwable {
        DorisProvider.DorisGlobalState dorisProvider_DorisGlobalState0 = new DorisProvider.DorisGlobalState();
        DorisOracleFactory dorisOracleFactory0 = DorisOracleFactory.GROUP_BY;
        TestOracle<DorisProvider.DorisGlobalState> testOracle0 = dorisOracleFactory0
                .create(dorisProvider_DorisGlobalState0);
        assertNotNull(testOracle0);
    }

    @Test
    public void test4() throws Throwable {
        DorisOracleFactory dorisOracleFactory0 = DorisOracleFactory.QUERY_PARTITIONING;
        DorisProvider.DorisGlobalState dorisProvider_DorisGlobalState0 = new DorisProvider.DorisGlobalState();
        try {
            dorisOracleFactory0.create(dorisProvider_DorisGlobalState0);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.doris.gen.DorisNewExpressionGenerator", e);
        }
    }

    @Test
    public void test5() throws Throwable {
        DorisOracleFactory dorisOracleFactory0 = DorisOracleFactory.HAVING;
        DorisProvider.DorisGlobalState dorisProvider_DorisGlobalState0 = new DorisProvider.DorisGlobalState();
        TestOracle<DorisProvider.DorisGlobalState> testOracle0 = dorisOracleFactory0
                .create(dorisProvider_DorisGlobalState0);
        assertNotNull(testOracle0);
    }

    @Test
    public void test6() throws Throwable {
        DorisProvider.DorisGlobalState dorisProvider_DorisGlobalState0 = new DorisProvider.DorisGlobalState();
        DorisOracleFactory dorisOracleFactory0 = DorisOracleFactory.ALL;
        try {
            dorisOracleFactory0.create(dorisProvider_DorisGlobalState0);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.doris.gen.DorisNewExpressionGenerator", e);
        }
    }
}
