/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 12 01:50:06 GMT 2025
 */

package sqlancer.evosuite.duckdb.test;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;
import sqlancer.duckdb.DuckDBProvider;
import sqlancer.duckdb.test.DuckDBQueryPartitioningHavingTester;

public class DuckDBQueryPartitioningHavingTester_ESTest {

    private void verifyException(String s, Exception e) {
    }

    @Test
    public void test0() throws Throwable {
        DuckDBQueryPartitioningHavingTester duckDBQueryPartitioningHavingTester0 = new DuckDBQueryPartitioningHavingTester(
                (DuckDBProvider.DuckDBGlobalState) null);
        // Undeclared exception!
        try {
            duckDBQueryPartitioningHavingTester0.check();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.duckdb.test.DuckDBQueryPartitioningBase", e);
        }
    }

    @Test
    public void test1() throws Throwable {
        DuckDBProvider.DuckDBGlobalState duckDBProvider_DuckDBGlobalState0 = new DuckDBProvider.DuckDBGlobalState();
        DuckDBQueryPartitioningHavingTester duckDBQueryPartitioningHavingTester0 = new DuckDBQueryPartitioningHavingTester(
                duckDBProvider_DuckDBGlobalState0);
        // Undeclared exception!
        try {
            duckDBQueryPartitioningHavingTester0.check();
            fail("Expecting exception: AssertionError");

        } catch (AssertionError e) {
            //
            // null
            //
        }
    }

    @Test
    public void test2() throws Throwable {
        DuckDBProvider.DuckDBGlobalState duckDBProvider_DuckDBGlobalState0 = new DuckDBProvider.DuckDBGlobalState();
        DuckDBQueryPartitioningHavingTester duckDBQueryPartitioningHavingTester0 = new DuckDBQueryPartitioningHavingTester(
                duckDBProvider_DuckDBGlobalState0);
        // Undeclared exception!
        try {
            duckDBQueryPartitioningHavingTester0.generateFetchColumns();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.duckdb.test.DuckDBQueryPartitioningHavingTester", e);
        }
    }

    @Test
    public void test3() throws Throwable {
        DuckDBProvider.DuckDBGlobalState duckDBProvider_DuckDBGlobalState0 = new DuckDBProvider.DuckDBGlobalState();
        DuckDBQueryPartitioningHavingTester duckDBQueryPartitioningHavingTester0 = new DuckDBQueryPartitioningHavingTester(
                duckDBProvider_DuckDBGlobalState0);
        // Undeclared exception!
        try {
            duckDBQueryPartitioningHavingTester0.generatePredicate();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.duckdb.test.DuckDBQueryPartitioningHavingTester", e);
        }
    }
}
